language: c

sudo: false

addons:
  apt:
    packages:
    - bc
    - libcurl4-openssl-dev

cache:
  directories:
    - vendor/libucl-0.7.3
    - vendor/libkqueue-2.0.3

script:
- ./configure
- make
- make check
